import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
import * as schema from './schema';
import path from 'path';
import { a1VideoModules, a1VideoLessons } from './a1-video-course-data';

const dbPath = process.env.DATABASE_URL || 'file:' + path.resolve(process.cwd(), 'sqlite.db');
const client = createClient({
  url: dbPath,
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const db = drizzle(client, { schema });
async function seed() {
  console.log('🌱 Starting comprehensive A1–A2 curriculum seed...');

  try {
    // Delete in correct order to respect foreign keys
    await db.delete(schema.userGrammarProgress);
    await db.delete(schema.userVocabularyProgress);
    await db.delete(schema.lessons);
    await db.delete(schema.modules);
    await db.delete(schema.vocabulary);
    await db.delete(schema.grammarPoints);

    // ========================================
    // MODULES — Full A1.1 (0-10), A1.2, A2.1, A2.2
    // ========================================
    console.log('Inserting modules...');
    const insertedModules = await db.insert(schema.modules).values([
      // A1.1 Modules
      { title: 'Module 0: German Survival Start', cefrLevel: 'A1.1', order: 1, description: 'Alphabet, pronunciation, umlauts, greetings, numbers, yes/no.' },
      { title: 'Module 1: Sich vorstellen', cefrLevel: 'A1.1', order: 2, description: 'Personal info, age, nationality, residence, languages, occupation.' },
      { title: 'Module 2: Familie und Personen', cefrLevel: 'A1.1', order: 3, description: 'Family, relationships, age, appearance, basic descriptions.' },
      { title: 'Module 3: Alltag', cefrLevel: 'A1.1', order: 4, description: 'Daily routine, school, work, time, appointments, weekdays.' },
      { title: 'Module 4: Essen und Trinken', cefrLevel: 'A1.1', order: 5, description: 'Food, drinks, restaurants, shopping, ordering.' },
      { title: 'Module 5: Einkaufen', cefrLevel: 'A1.1', order: 6, description: 'Prices, clothes, sizes, quantities, colors, supermarket.' },
      { title: 'Module 6: Wohnen', cefrLevel: 'A1.1', order: 7, description: 'Home, rooms, furniture, address, location.' },
      { title: 'Module 7: Freizeit', cefrLevel: 'A1.1', order: 8, description: 'Hobbies, music, sports, cinema, weekend, invitations.' },
      { title: 'Module 8: Unterwegs', cefrLevel: 'A1.1', order: 9, description: 'Transport, directions, places, train station, tickets.' },
      { title: 'Module 9: Gesundheit', cefrLevel: 'A1.1', order: 10, description: 'Body parts, symptoms, doctor, pharmacy, basic problems.' },
      { title: 'Module 10: A1 Integration', cefrLevel: 'A1.1', order: 11, description: 'Combine all core grammar, vocabulary, skills, and real-world scenarios.' },
      // A1.2 Modules
      { title: 'Module 11: Reisen & Urlaub', cefrLevel: 'A1.2', order: 12, description: 'Travel, booking, hotel, vacation plans.' },
      { title: 'Module 12: Termine & Verabredungen', cefrLevel: 'A1.2', order: 13, description: 'Appointments, services, scheduling, phone calls.' },
      { title: 'Module 13: Arbeit & Beruf', cefrLevel: 'A1.2', order: 14, description: 'Work, job descriptions, workplace communication.' },
      { title: 'Module 14: Wetter & Jahreszeiten', cefrLevel: 'A1.2', order: 15, description: 'Weather, seasons, climate, outdoor activities.' },
      { title: 'Module 15: Nachrichten & Medien', cefrLevel: 'A1.2', order: 16, description: 'Messages, simple emails, notes, invitations.' },
      // A2.1 Modules
      { title: 'Module 16: Berufsleben', cefrLevel: 'A2.1', order: 17, description: 'Professional life, applications, interviews, work routines.' },
      { title: 'Module 17: Stadtleben', cefrLevel: 'A2.1', order: 18, description: 'City life, public services, local events, neighborhoods.' },
      { title: 'Module 18: Mobilität', cefrLevel: 'A2.1', order: 19, description: 'Transport, driving, cycling, public transit, problems.' },
      { title: 'Module 19: Lernen & Bildung', cefrLevel: 'A2.1', order: 20, description: 'Education, courses, languages, skills, certificates.' },
      { title: 'Module 20: Beziehungen', cefrLevel: 'A2.1', order: 21, description: 'Relationships, emotions, feelings, social life, conflicts.' },
      // A2.2 Modules
      { title: 'Module 21: Erfahrungen', cefrLevel: 'A2.2', order: 22, description: 'Past experiences, storytelling, travel memories, achievements.' },
      { title: 'Module 22: Pläne & Zukunft', cefrLevel: 'A2.2', order: 23, description: 'Future plans, goals, intentions, wishes, arrangements.' },
      { title: 'Module 23: Meinungen', cefrLevel: 'A2.2', order: 24, description: 'Opinions, preferences, comparisons, reasons, arguments.' },
      { title: 'Module 24: Probleme lösen', cefrLevel: 'A2.2', order: 25, description: 'Problems, complaints, requests, simple formal communication.' },
      { title: 'Module 25: A2 Integration', cefrLevel: 'A2.2', order: 26, description: 'Final integration of all A2 skills, Goethe A2 exam preparation.' },
      // A1 Video Course Modules
      ...a1VideoModules.map(m => ({ title: m.title, cefrLevel: 'A1.1', order: m.order, description: m.description }))
    ]).returning({ id: schema.modules.id, order: schema.modules.order });

    const modMap: Record<number, number> = {};
    insertedModules.forEach(m => { modMap[m.order] = m.id; });

    // ========================================
    // LESSONS — 3-4 lessons per module
    // ========================================
    console.log('Inserting lessons...');
    const lessonsData = [
      // Module 0: Survival
      { moduleId: modMap[1], title: 'The German Alphabet & Pronunciation', order: 1, type: 'vocabulary', content: { info: "Letters, umlauts (ä, ö, ü), ß, pronunciation rules." } },
      { moduleId: modMap[1], title: 'Greetings & Polite Expressions', order: 2, type: 'vocabulary', content: { info: "Hallo, Guten Morgen, Bitte, Danke, Auf Wiedersehen." } },
      { moduleId: modMap[1], title: 'Numbers 0–100 & Phone Numbers', order: 3, type: 'vocabulary', content: { info: "Counting, phone numbers, spelling numbers." } },
      { moduleId: modMap[1], title: 'Grammar: W-Fragen & Ja/Nein-Fragen', order: 4, type: 'grammar', content: { info: "Question formation: Wie? Was? Wo? Woher?" } },
      // Module 1: Introductions
      { moduleId: modMap[2], title: 'Vocabulary: Personal Information', order: 1, type: 'vocabulary', content: { info: "Name, age, nationality, residence, languages." } },
      { moduleId: modMap[2], title: 'Grammar: sein & haben', order: 2, type: 'grammar', content: { info: "Conjugation of sein (to be) and haben (to have)." } },
      { moduleId: modMap[2], title: 'Grammar: Present Tense Verbs', order: 3, type: 'grammar', content: { info: "Regular verb conjugation: -e, -st, -t, -en." } },
      { moduleId: modMap[2], title: 'Conversation: Introduce Yourself', order: 4, type: 'conversation', content: { info: "Introduce yourself naturally without reading." } },
      // Module 2: Family
      { moduleId: modMap[3], title: 'Vocabulary: Family Members', order: 1, type: 'vocabulary', content: { info: "Mutter, Vater, Bruder, Schwester, Kinder." } },
      { moduleId: modMap[3], title: 'Grammar: Possessive Determiners', order: 2, type: 'grammar', content: { info: "mein, dein, sein, ihr, unser, euer." } },
      { moduleId: modMap[3], title: 'Grammar: Articles & Plural', order: 3, type: 'grammar', content: { info: "der/die/das, ein/eine, plural forms." } },
      { moduleId: modMap[3], title: 'Reading: Family Description', order: 4, type: 'reading', content: { info: "Read and understand a family introduction." } },
      // Module 3: Daily Life
      { moduleId: modMap[4], title: 'Vocabulary: Daily Routine', order: 1, type: 'vocabulary', content: { info: "aufstehen, frühstücken, arbeiten, schlafen." } },
      { moduleId: modMap[4], title: 'Grammar: Separable Verbs', order: 2, type: 'grammar', content: { info: "aufstehen, einkaufen, fernsehen — prefix separates." } },
      { moduleId: modMap[4], title: 'Vocabulary: Time & Weekdays', order: 3, type: 'vocabulary', content: { info: "Montag, Dienstag, Uhrzeit, morgens, abends." } },
      { moduleId: modMap[4], title: 'Listening: A Typical Day', order: 4, type: 'listening', content: { info: "Listen and answer questions about someone's day." } },
      // Module 4: Food
      { moduleId: modMap[5], title: 'Vocabulary: Food & Drinks', order: 1, type: 'vocabulary', content: { info: "Brot, Käse, Wasser, Kaffee, Obst, Gemüse." } },
      { moduleId: modMap[5], title: 'Grammar: Accusative Case', order: 2, type: 'grammar', content: { info: "Ich kaufe den Kaffee. der → den in accusative." } },
      { moduleId: modMap[5], title: 'Grammar: kein/nicht & möchte', order: 3, type: 'grammar', content: { info: "Negation and modal verb möchte." } },
      { moduleId: modMap[5], title: 'Conversation: Restaurant Simulation', order: 4, type: 'conversation', content: { info: "Order food and drinks at a restaurant." } },
      // Module 5: Shopping
      { moduleId: modMap[6], title: 'Vocabulary: Clothes & Colors', order: 1, type: 'vocabulary', content: { info: "Hemd, Hose, Kleid, rot, blau, schwarz." } },
      { moduleId: modMap[6], title: 'Grammar: Accusative & Plural', order: 2, type: 'grammar', content: { info: "Using accusative with shopping context." } },
      { moduleId: modMap[6], title: 'Conversation: Shop Simulation', order: 3, type: 'conversation', content: { info: "Buy clothes, ask about sizes and prices." } },
      // Module 6: Living
      { moduleId: modMap[7], title: 'Vocabulary: Rooms & Furniture', order: 1, type: 'vocabulary', content: { info: "Küche, Schlafzimmer, Tisch, Stuhl, Bett." } },
      { moduleId: modMap[7], title: 'Grammar: Prepositions & es gibt', order: 2, type: 'grammar', content: { info: "in, auf, unter, neben. Es gibt einen Tisch." } },
      { moduleId: modMap[7], title: 'Listening: Apartment Description', order: 3, type: 'listening', content: { info: "Listen to someone describe their apartment." } },
      // Module 7: Free Time
      { moduleId: modMap[8], title: 'Vocabulary: Hobbies & Sports', order: 1, type: 'vocabulary', content: { info: "Tennis, lesen, schwimmen, Musik hören." } },
      { moduleId: modMap[8], title: 'Grammar: Modal Verbs & gern', order: 2, type: 'grammar', content: { info: "können, wollen, mögen, gern + verb." } },
      { moduleId: modMap[8], title: 'Conversation: Planning the Weekend', order: 3, type: 'conversation', content: { info: "Invite a friend and make plans." } },
      // Module 8: Getting Around
      { moduleId: modMap[9], title: 'Vocabulary: Places & Transport', order: 1, type: 'vocabulary', content: { info: "Bahnhof, Bus, Straßenbahn, Fahrkarte." } },
      { moduleId: modMap[9], title: 'Grammar: Prepositions & Imperative', order: 2, type: 'grammar', content: { info: "zu, nach, in. Gehen Sie geradeaus!" } },
      { moduleId: modMap[9], title: 'Conversation: At the Train Station', order: 3, type: 'conversation', content: { info: "Buy a ticket and find your platform." } },
      // Module 9: Health
      { moduleId: modMap[10], title: 'Vocabulary: Body & Symptoms', order: 1, type: 'vocabulary', content: { info: "Kopf, Arm, Bauch, Schmerzen, Fieber." } },
      { moduleId: modMap[10], title: 'Grammar: müssen & können', order: 2, type: 'grammar', content: { info: "Sie müssen im Bett bleiben." } },
      { moduleId: modMap[10], title: 'Conversation: At the Doctor', order: 3, type: 'conversation', content: { info: "Describe symptoms and understand advice." } },
      // Module 10: Integration
      { moduleId: modMap[11], title: 'A1 Grammar Review', order: 1, type: 'grammar', content: { info: "All A1.1 grammar in one practice session." } },
      { moduleId: modMap[11], title: 'A1 Vocabulary Review', order: 2, type: 'vocabulary', content: { info: "Core A1 vocabulary across all topics." } },
      { moduleId: modMap[11], title: 'A1 Goethe Exam Simulation', order: 3, type: 'reading', content: { info: "Practice Goethe A1 Lesen/Hören/Schreiben tasks." } },
      // A1.2 Modules (12-16)
      { moduleId: modMap[12], title: 'Vocabulary: Travel & Hotels', order: 1, type: 'vocabulary', content: { info: "Flugzeug, Hotel, Zimmer, buchen, Reise." } },
      { moduleId: modMap[12], title: 'Grammar: Perfect Tense Introduction', order: 2, type: 'grammar', content: { info: "Ich habe gearbeitet. Ich bin gefahren." } },
      { moduleId: modMap[12], title: 'Conversation: Booking a Hotel', order: 3, type: 'conversation', content: { info: "Reserve a room and ask about facilities." } },
      { moduleId: modMap[13], title: 'Vocabulary: Appointments', order: 1, type: 'vocabulary', content: { info: "Termin, Uhrzeit, verschieben, absagen." } },
      { moduleId: modMap[13], title: 'Grammar: Conjunctions (und, aber, oder)', order: 2, type: 'grammar', content: { info: "Connecting sentences with conjunctions." } },
      { moduleId: modMap[13], title: 'Listening: Phone Call', order: 3, type: 'listening', content: { info: "Listen to appointment scheduling." } },
      { moduleId: modMap[14], title: 'Vocabulary: Jobs & Workplace', order: 1, type: 'vocabulary', content: { info: "Büro, Kollege, Chef, Besprechung." } },
      { moduleId: modMap[14], title: 'Grammar: More Modal Verbs', order: 2, type: 'grammar', content: { info: "dürfen, sollen + workplace contexts." } },
      { moduleId: modMap[15], title: 'Vocabulary: Weather', order: 1, type: 'vocabulary', content: { info: "Sonne, Regen, kalt, warm, Frühling." } },
      { moduleId: modMap[15], title: 'Grammar: Comparative Basics', order: 2, type: 'grammar', content: { info: "groß → größer, gut → besser." } },
      { moduleId: modMap[16], title: 'Writing: Short Email', order: 1, type: 'reading', content: { info: "Write an invitation email to a friend." } },
      { moduleId: modMap[16], title: 'Grammar: Dative Introduction', order: 2, type: 'grammar', content: { info: "Ich gebe dem Mann das Buch." } },
      // A2.1 Modules (17-21)
      { moduleId: modMap[17], title: 'Vocabulary: Professional Life', order: 1, type: 'vocabulary', content: { info: "Bewerbung, Lebenslauf, Gehalt, Vertrag." } },
      { moduleId: modMap[17], title: 'Grammar: Perfekt Systematically', order: 2, type: 'grammar', content: { info: "Regular and irregular past participles." } },
      { moduleId: modMap[18], title: 'Vocabulary: City Services', order: 1, type: 'vocabulary', content: { info: "Rathaus, Bibliothek, Amt, Formular." } },
      { moduleId: modMap[18], title: 'Grammar: weil & dass Clauses', order: 2, type: 'grammar', content: { info: "Subordinate clauses with verb at end." } },
      { moduleId: modMap[19], title: 'Vocabulary: Transport Problems', order: 1, type: 'vocabulary', content: { info: "Verspätung, Umleitung, Stau, Panne." } },
      { moduleId: modMap[19], title: 'Grammar: Reflexive Verbs', order: 2, type: 'grammar', content: { info: "sich freuen, sich anmelden, sich fühlen." } },
      { moduleId: modMap[20], title: 'Vocabulary: Education', order: 1, type: 'vocabulary', content: { info: "Kurs, Prüfung, Zeugnis, Ergebnis." } },
      { moduleId: modMap[20], title: 'Grammar: wenn Clauses', order: 2, type: 'grammar', content: { info: "Wenn ich Zeit habe, lerne ich Deutsch." } },
      { moduleId: modMap[21], title: 'Vocabulary: Emotions', order: 1, type: 'vocabulary', content: { info: "glücklich, traurig, wütend, aufgeregt." } },
      { moduleId: modMap[21], title: 'Grammar: Adjective Endings', order: 2, type: 'grammar', content: { info: "der große Mann, ein großer Mann." } },
      // A2.2 Modules (22-26)
      { moduleId: modMap[22], title: 'Vocabulary: Experiences', order: 1, type: 'vocabulary', content: { info: "Erinnerung, Erlebnis, Reise, Abenteuer." } },
      { moduleId: modMap[22], title: 'Grammar: Präteritum', order: 2, type: 'grammar', content: { info: "war, hatte, ging, kam — simple past of common verbs." } },
      { moduleId: modMap[23], title: 'Vocabulary: Future Plans', order: 1, type: 'vocabulary', content: { info: "Ziel, Plan, Absicht, Wunsch, Traum." } },
      { moduleId: modMap[23], title: 'Grammar: Superlative', order: 2, type: 'grammar', content: { info: "am größten, am besten, am schönsten." } },
      { moduleId: modMap[24], title: 'Vocabulary: Opinions', order: 1, type: 'vocabulary', content: { info: "Meinung, finden, glauben, denken." } },
      { moduleId: modMap[24], title: 'Grammar: obwohl & Conjunctions', order: 2, type: 'grammar', content: { info: "Concessive clauses and complex connectors." } },
      { moduleId: modMap[25], title: 'Vocabulary: Problems & Complaints', order: 1, type: 'vocabulary', content: { info: "Beschwerde, Problem, Lösung, reklamieren." } },
      { moduleId: modMap[25], title: 'Grammar: Two-Way Prepositions', order: 2, type: 'grammar', content: { info: "Wechselpräpositionen: in, an, auf + Akk/Dat." } },
      { moduleId: modMap[26], title: 'A2 Comprehensive Review', order: 1, type: 'grammar', content: { info: "All A2 grammar and vocabulary review." } },
      { moduleId: modMap[26], title: 'A2 Goethe Practice Exam', order: 2, type: 'reading', content: { info: "Complete A2 exam simulation." } },
      
      ...a1VideoLessons.map(l => ({
        moduleId: modMap[l.modId],
        title: l.title,
        order: l.order,
        type: 'video' as const,
        content: l.content
      }))
    ];

    await db.insert(schema.lessons).values(lessonsData);

    // ========================================
    // VOCABULARY — 200+ Goethe-aligned A1 words
    // ========================================
    console.log('Inserting vocabulary...');
    const vocabData = [
      // Greetings & Basics
      { germanWord: 'Hallo', englishMeaning: 'Hello', partOfSpeech: 'interjection', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Guten Morgen', englishMeaning: 'Good morning', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Guten Tag', englishMeaning: 'Good day', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Guten Abend', englishMeaning: 'Good evening', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Tschüss', englishMeaning: 'Bye', partOfSpeech: 'interjection', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Auf Wiedersehen', englishMeaning: 'Goodbye', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Bitte', englishMeaning: 'Please / You\'re welcome', partOfSpeech: 'interjection', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Danke', englishMeaning: 'Thank you', partOfSpeech: 'interjection', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Ja', englishMeaning: 'Yes', partOfSpeech: 'interjection', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'Nein', englishMeaning: 'No', partOfSpeech: 'interjection', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'Entschuldigung', englishMeaning: 'Excuse me / Sorry', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Greetings', article: 'die' },
      // Personal Info
      { germanWord: 'Name', englishMeaning: 'Name', article: 'der', plural: 'Namen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal', exampleSentence: 'Mein Name ist Max.' },
      { germanWord: 'Alter', englishMeaning: 'Age', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Land', englishMeaning: 'Country', article: 'das', plural: 'Länder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal', exampleSentence: 'Ich komme aus einem anderen Land.' },
      { germanWord: 'Sprache', englishMeaning: 'Language', article: 'die', plural: 'Sprachen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Beruf', englishMeaning: 'Profession', article: 'der', plural: 'Berufe', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Adresse', englishMeaning: 'Address', article: 'die', plural: 'Adressen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Telefonnummer', englishMeaning: 'Phone number', article: 'die', plural: 'Telefonnummern', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      // Family
      { germanWord: 'Familie', englishMeaning: 'Family', article: 'die', plural: 'Familien', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family', exampleSentence: 'Meine Familie wohnt in Berlin.' },
      { germanWord: 'Mutter', englishMeaning: 'Mother', article: 'die', plural: 'Mütter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Vater', englishMeaning: 'Father', article: 'der', plural: 'Väter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Bruder', englishMeaning: 'Brother', article: 'der', plural: 'Brüder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Schwester', englishMeaning: 'Sister', article: 'die', plural: 'Schwestern', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Kind', englishMeaning: 'Child', article: 'das', plural: 'Kinder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family', exampleSentence: 'Das Kind spielt im Garten.' },
      { germanWord: 'Eltern', englishMeaning: 'Parents', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Frau', englishMeaning: 'Woman / Wife', article: 'die', plural: 'Frauen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Mann', englishMeaning: 'Man / Husband', article: 'der', plural: 'Männer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Freund', englishMeaning: 'Friend (m)', article: 'der', plural: 'Freunde', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Freundin', englishMeaning: 'Friend (f)', article: 'die', plural: 'Freundinnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      // Daily Life
      { germanWord: 'Tag', englishMeaning: 'Day', article: 'der', plural: 'Tage', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Uhr', englishMeaning: 'Clock / O\'clock', article: 'die', plural: 'Uhren', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life', exampleSentence: 'Es ist drei Uhr.' },
      { germanWord: 'Zeit', englishMeaning: 'Time', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Morgen', englishMeaning: 'Morning', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Abend', englishMeaning: 'Evening', article: 'der', plural: 'Abende', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Nacht', englishMeaning: 'Night', article: 'die', plural: 'Nächte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Stunde', englishMeaning: 'Hour', article: 'die', plural: 'Stunden', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Minute', englishMeaning: 'Minute', article: 'die', plural: 'Minuten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Woche', englishMeaning: 'Week', article: 'die', plural: 'Wochen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      // Food & Drinks
      { germanWord: 'Wasser', englishMeaning: 'Water', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Kaffee', englishMeaning: 'Coffee', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food', exampleSentence: 'Ich möchte einen Kaffee.' },
      { germanWord: 'Tee', englishMeaning: 'Tea', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Brot', englishMeaning: 'Bread', article: 'das', plural: 'Brote', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Käse', englishMeaning: 'Cheese', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Milch', englishMeaning: 'Milk', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Ei', englishMeaning: 'Egg', article: 'das', plural: 'Eier', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Fleisch', englishMeaning: 'Meat', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Fisch', englishMeaning: 'Fish', article: 'der', plural: 'Fische', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Obst', englishMeaning: 'Fruit', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Gemüse', englishMeaning: 'Vegetables', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Apfel', englishMeaning: 'Apple', article: 'der', plural: 'Äpfel', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Kuchen', englishMeaning: 'Cake', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Suppe', englishMeaning: 'Soup', article: 'die', plural: 'Suppen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Salat', englishMeaning: 'Salad', article: 'der', plural: 'Salate', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      // Living
      { germanWord: 'Haus', englishMeaning: 'House', article: 'das', plural: 'Häuser', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living', exampleSentence: 'Das Haus ist groß.' },
      { germanWord: 'Wohnung', englishMeaning: 'Apartment', article: 'die', plural: 'Wohnungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Zimmer', englishMeaning: 'Room', article: 'das', plural: 'Zimmer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Küche', englishMeaning: 'Kitchen', article: 'die', plural: 'Küchen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Bad', englishMeaning: 'Bathroom', article: 'das', plural: 'Bäder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Schlafzimmer', englishMeaning: 'Bedroom', article: 'das', plural: 'Schlafzimmer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Tisch', englishMeaning: 'Table', article: 'der', plural: 'Tische', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Stuhl', englishMeaning: 'Chair', article: 'der', plural: 'Stühle', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Bett', englishMeaning: 'Bed', article: 'das', plural: 'Betten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      // Transport
      { germanWord: 'Bahnhof', englishMeaning: 'Train station', article: 'der', plural: 'Bahnhöfe', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Bus', englishMeaning: 'Bus', article: 'der', plural: 'Busse', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Zug', englishMeaning: 'Train', article: 'der', plural: 'Züge', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Auto', englishMeaning: 'Car', article: 'das', plural: 'Autos', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Fahrrad', englishMeaning: 'Bicycle', article: 'das', plural: 'Fahrräder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Fahrkarte', englishMeaning: 'Ticket', article: 'die', plural: 'Fahrkarten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Straße', englishMeaning: 'Street', article: 'die', plural: 'Straßen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      // Health
      { germanWord: 'Arzt', englishMeaning: 'Doctor', article: 'der', plural: 'Ärzte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Kopf', englishMeaning: 'Head', article: 'der', plural: 'Köpfe', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Arm', englishMeaning: 'Arm', article: 'der', plural: 'Arme', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Bein', englishMeaning: 'Leg', article: 'das', plural: 'Beine', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Auge', englishMeaning: 'Eye', article: 'das', plural: 'Augen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Apotheke', englishMeaning: 'Pharmacy', article: 'die', plural: 'Apotheken', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      // Core Verbs
      { germanWord: 'sein', englishMeaning: 'to be', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich bin Student.' },
      { germanWord: 'haben', englishMeaning: 'to have', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich habe ein Buch.' },
      { germanWord: 'machen', englishMeaning: 'to make / to do', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'gehen', englishMeaning: 'to go', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich gehe nach Hause.' },
      { germanWord: 'kommen', englishMeaning: 'to come', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Woher kommst du?' },
      { germanWord: 'wohnen', englishMeaning: 'to live (reside)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich wohne in Berlin.' },
      { germanWord: 'sprechen', englishMeaning: 'to speak', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich spreche Deutsch.' },
      { germanWord: 'lernen', englishMeaning: 'to learn', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich lerne Deutsch.' },
      { germanWord: 'arbeiten', englishMeaning: 'to work', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'heißen', englishMeaning: 'to be called', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich heiße Anna.' },
      { germanWord: 'essen', englishMeaning: 'to eat', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'trinken', englishMeaning: 'to drink', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'kaufen', englishMeaning: 'to buy', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich kaufe einen Kaffee.' },
      { germanWord: 'lesen', englishMeaning: 'to read', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'schreiben', englishMeaning: 'to write', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'schlafen', englishMeaning: 'to sleep', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'fahren', englishMeaning: 'to drive / to go (by vehicle)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'finden', englishMeaning: 'to find', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'spielen', englishMeaning: 'to play', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'kochen', englishMeaning: 'to cook', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'brauchen', englishMeaning: 'to need', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'möchten', englishMeaning: 'would like', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Ich möchte ein Wasser.' },
      { germanWord: 'können', englishMeaning: 'can / to be able to', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'müssen', englishMeaning: 'must / to have to', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'wollen', englishMeaning: 'to want', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      // Adjectives
      { germanWord: 'groß', englishMeaning: 'big / tall', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'klein', englishMeaning: 'small / short', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'gut', englishMeaning: 'good', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives', exampleSentence: 'Das ist sehr gut.' },
      { germanWord: 'schlecht', englishMeaning: 'bad', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'schön', englishMeaning: 'beautiful', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'neu', englishMeaning: 'new', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'alt', englishMeaning: 'old', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'teuer', englishMeaning: 'expensive', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'billig', englishMeaning: 'cheap', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'kalt', englishMeaning: 'cold', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'warm', englishMeaning: 'warm', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'schnell', englishMeaning: 'fast', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'langsam', englishMeaning: 'slow', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      // Places
      { germanWord: 'Schule', englishMeaning: 'School', article: 'die', plural: 'Schulen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Universität', englishMeaning: 'University', article: 'die', plural: 'Universitäten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Supermarkt', englishMeaning: 'Supermarket', article: 'der', plural: 'Supermärkte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Restaurant', englishMeaning: 'Restaurant', article: 'das', plural: 'Restaurants', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Krankenhaus', englishMeaning: 'Hospital', article: 'das', plural: 'Krankenhäuser', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Stadt', englishMeaning: 'City', article: 'die', plural: 'Städte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Büro', englishMeaning: 'Office', article: 'das', plural: 'Büros', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      // Colors
      { germanWord: 'rot', englishMeaning: 'red', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Colors' },
      { germanWord: 'blau', englishMeaning: 'blue', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Colors' },
      { germanWord: 'grün', englishMeaning: 'green', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Colors' },
      { germanWord: 'schwarz', englishMeaning: 'black', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Colors' },
      { germanWord: 'weiß', englishMeaning: 'white', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Colors' },
      { germanWord: 'gelb', englishMeaning: 'yellow', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Colors' },
      // Clothes
      { germanWord: 'Hemd', englishMeaning: 'Shirt', article: 'das', plural: 'Hemden', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Hose', englishMeaning: 'Trousers', article: 'die', plural: 'Hosen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Kleid', englishMeaning: 'Dress', article: 'das', plural: 'Kleider', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Schuh', englishMeaning: 'Shoe', article: 'der', plural: 'Schuhe', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      // Common phrases / other
      { germanWord: 'Geld', englishMeaning: 'Money', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Buch', englishMeaning: 'Book', article: 'das', plural: 'Bücher', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Handy', englishMeaning: 'Mobile phone', article: 'das', plural: 'Handys', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Computer', englishMeaning: 'Computer', article: 'der', plural: 'Computer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Zeitung', englishMeaning: 'Newspaper', article: 'die', plural: 'Zeitungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Musik', englishMeaning: 'Music', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Film', englishMeaning: 'Film / Movie', article: 'der', plural: 'Filme', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Sport', englishMeaning: 'Sport', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      // More verbs
      { germanWord: 'verstehen', englishMeaning: 'to understand', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'sehen', englishMeaning: 'to see', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'hören', englishMeaning: 'to hear / listen', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'fragen', englishMeaning: 'to ask', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'antworten', englishMeaning: 'to answer', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'helfen', englishMeaning: 'to help', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'bezahlen', englishMeaning: 'to pay', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'kennen', englishMeaning: 'to know (person/thing)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'wissen', englishMeaning: 'to know (fact)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      // Prepositions & function words
      { germanWord: 'in', englishMeaning: 'in / into', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'mit', englishMeaning: 'with', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'von', englishMeaning: 'from / of', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'nach', englishMeaning: 'to / after', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'für', englishMeaning: 'for', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'heute', englishMeaning: 'today', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'morgen', englishMeaning: 'tomorrow', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'gestern', englishMeaning: 'yesterday', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'hier', englishMeaning: 'here', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'dort', englishMeaning: 'there', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'viel', englishMeaning: 'much / a lot', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'wenig', englishMeaning: 'little / few', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'immer', englishMeaning: 'always', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'nie', englishMeaning: 'never', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'manchmal', englishMeaning: 'sometimes', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'oft', englishMeaning: 'often', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Basics' },
      // ========================================
      // EXPANDED GOETHE A1 VOCABULARY (~500 additional words)
      // ========================================
      // --- Months ---
      { germanWord: 'Januar', englishMeaning: 'January', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Februar', englishMeaning: 'February', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'März', englishMeaning: 'March', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'April', englishMeaning: 'April', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Mai', englishMeaning: 'May', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Juni', englishMeaning: 'June', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Juli', englishMeaning: 'July', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'August', englishMeaning: 'August', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'September', englishMeaning: 'September', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Oktober', englishMeaning: 'October', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'November', englishMeaning: 'November', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Dezember', englishMeaning: 'December', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      // --- Seasons ---
      { germanWord: 'Frühling', englishMeaning: 'Spring', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Sommer', englishMeaning: 'Summer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Herbst', englishMeaning: 'Autumn', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Winter', englishMeaning: 'Winter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      // --- Days of the Week ---
      { germanWord: 'Montag', englishMeaning: 'Monday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Dienstag', englishMeaning: 'Tuesday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Mittwoch', englishMeaning: 'Wednesday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Donnerstag', englishMeaning: 'Thursday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Freitag', englishMeaning: 'Friday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Samstag', englishMeaning: 'Saturday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Sonntag', englishMeaning: 'Sunday', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'der' },
      { germanWord: 'Wochenende', englishMeaning: 'Weekend', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', article: 'das' },
      // --- Countries & Nationalities ---
      { germanWord: 'Deutschland', englishMeaning: 'Germany', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'Österreich', englishMeaning: 'Austria', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'die Schweiz', englishMeaning: 'Switzerland', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'Frankreich', englishMeaning: 'France', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'England', englishMeaning: 'England', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'Italien', englishMeaning: 'Italy', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'Spanien', englishMeaning: 'Spain', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'die Türkei', englishMeaning: 'Turkey', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'Russland', englishMeaning: 'Russia', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'China', englishMeaning: 'China', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'Indien', englishMeaning: 'India', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'deutsch', englishMeaning: 'German (adj.)', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'türkisch', englishMeaning: 'Turkish (adj.)', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Countries' },
      { germanWord: 'englisch', englishMeaning: 'English (adj.)', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Countries' },
      // --- Professions (Goethe A1 essential) ---
      { germanWord: 'Lehrer', englishMeaning: 'Teacher (m)', article: 'der', plural: 'Lehrer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Lehrerin', englishMeaning: 'Teacher (f)', article: 'die', plural: 'Lehrerinnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Student', englishMeaning: 'Student (m)', article: 'der', plural: 'Studenten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work', exampleSentence: 'Ich bin Student.' },
      { germanWord: 'Studentin', englishMeaning: 'Student (f)', article: 'die', plural: 'Studentinnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Ärztin', englishMeaning: 'Doctor (f)', article: 'die', plural: 'Ärztinnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Ingenieur', englishMeaning: 'Engineer (m)', article: 'der', plural: 'Ingenieure', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Verkäufer', englishMeaning: 'Salesperson (m)', article: 'der', plural: 'Verkäufer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Verkäuferin', englishMeaning: 'Salesperson (f)', article: 'die', plural: 'Verkäuferinnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Krankenschwester', englishMeaning: 'Nurse (f)', article: 'die', plural: 'Krankenschwestern', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Polizist', englishMeaning: 'Police officer (m)', article: 'der', plural: 'Polizisten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Koch', englishMeaning: 'Cook (m)', article: 'der', plural: 'Köche', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Kellner', englishMeaning: 'Waiter', article: 'der', plural: 'Kellner', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Sekretärin', englishMeaning: 'Secretary (f)', article: 'die', plural: 'Sekretärinnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Hausfrau', englishMeaning: 'Housewife', article: 'die', plural: 'Hausfrauen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      { germanWord: 'Taxifahrer', englishMeaning: 'Taxi driver', article: 'der', plural: 'Taxifahrer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Work' },
      // --- Weather ---
      { germanWord: 'Wetter', englishMeaning: 'Weather', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'Sonne', englishMeaning: 'Sun', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'Regen', englishMeaning: 'Rain', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'Schnee', englishMeaning: 'Snow', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'Wind', englishMeaning: 'Wind', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'Wolke', englishMeaning: 'Cloud', article: 'die', plural: 'Wolken', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'Grad', englishMeaning: 'Degree', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Weather' },
      { germanWord: 'regnen', englishMeaning: 'to rain', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Weather', exampleSentence: 'Es regnet.' },
      { germanWord: 'scheinen', englishMeaning: 'to shine', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Weather', exampleSentence: 'Die Sonne scheint.' },
      // --- Body Parts (expanded) ---
      { germanWord: 'Hand', englishMeaning: 'Hand', article: 'die', plural: 'Hände', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Fuß', englishMeaning: 'Foot', article: 'der', plural: 'Füße', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Rücken', englishMeaning: 'Back', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Bauch', englishMeaning: 'Belly/Stomach', article: 'der', plural: 'Bäuche', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Zahn', englishMeaning: 'Tooth', article: 'der', plural: 'Zähne', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Ohr', englishMeaning: 'Ear', article: 'das', plural: 'Ohren', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Nase', englishMeaning: 'Nose', article: 'die', plural: 'Nasen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Mund', englishMeaning: 'Mouth', article: 'der', plural: 'Münder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Haar', englishMeaning: 'Hair', article: 'das', plural: 'Haare', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Finger', englishMeaning: 'Finger', article: 'der', plural: 'Finger', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Hals', englishMeaning: 'Throat/Neck', article: 'der', plural: 'Hälse', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      // --- Health (expanded) ---
      { germanWord: 'Schmerzen', englishMeaning: 'Pain', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health', exampleSentence: 'Ich habe Kopfschmerzen.' },
      { germanWord: 'Fieber', englishMeaning: 'Fever', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Husten', englishMeaning: 'Cough', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Schnupfen', englishMeaning: 'Cold (runny nose)', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Medikament', englishMeaning: 'Medicine', article: 'das', plural: 'Medikamente', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'Rezept', englishMeaning: 'Prescription/Recipe', article: 'das', plural: 'Rezepte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Health' },
      { germanWord: 'krank', englishMeaning: 'sick/ill', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Health', exampleSentence: 'Ich bin krank.' },
      { germanWord: 'gesund', englishMeaning: 'healthy', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Health' },
      // --- Furniture (expanded) ---
      { germanWord: 'Schrank', englishMeaning: 'Wardrobe/Cabinet', article: 'der', plural: 'Schränke', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Regal', englishMeaning: 'Shelf', article: 'das', plural: 'Regale', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Sofa', englishMeaning: 'Sofa', article: 'das', plural: 'Sofas', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Lampe', englishMeaning: 'Lamp', article: 'die', plural: 'Lampen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Spiegel', englishMeaning: 'Mirror', article: 'der', plural: 'Spiegel', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Fenster', englishMeaning: 'Window', article: 'das', plural: 'Fenster', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Tür', englishMeaning: 'Door', article: 'die', plural: 'Türen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Wohnzimmer', englishMeaning: 'Living room', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Garten', englishMeaning: 'Garden', article: 'der', plural: 'Gärten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Balkon', englishMeaning: 'Balcony', article: 'der', plural: 'Balkone', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Garage', englishMeaning: 'Garage', article: 'die', plural: 'Garagen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Miete', englishMeaning: 'Rent', article: 'die', plural: 'Mieten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living' },
      { germanWord: 'Stock', englishMeaning: 'Floor (storey)', article: 'der', plural: 'Stockwerke', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Living', exampleSentence: 'Ich wohne im zweiten Stock.' },
      // --- Post/Bank/Services ---
      { germanWord: 'Brief', englishMeaning: 'Letter', article: 'der', plural: 'Briefe', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Post', englishMeaning: 'Post/Mail', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Bank', englishMeaning: 'Bank', article: 'die', plural: 'Banken', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Formular', englishMeaning: 'Form (document)', article: 'das', plural: 'Formulare', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Ausweis', englishMeaning: 'ID card', article: 'der', plural: 'Ausweise', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Pass', englishMeaning: 'Passport', article: 'der', plural: 'Pässe', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Unterschrift', englishMeaning: 'Signature', article: 'die', plural: 'Unterschriften', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Amt', englishMeaning: 'Office (government)', article: 'das', plural: 'Ämter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Anmeldung', englishMeaning: 'Registration', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services' },
      { germanWord: 'Termin', englishMeaning: 'Appointment', article: 'der', plural: 'Termine', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Services', exampleSentence: 'Ich habe einen Termin.' },
      // --- School/Education ---
      { germanWord: 'Kurs', englishMeaning: 'Course', article: 'der', plural: 'Kurse', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Prüfung', englishMeaning: 'Exam', article: 'die', plural: 'Prüfungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Hausaufgabe', englishMeaning: 'Homework', article: 'die', plural: 'Hausaufgaben', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Klasse', englishMeaning: 'Class', article: 'die', plural: 'Klassen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Lektion', englishMeaning: 'Lesson', article: 'die', plural: 'Lektionen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Übung', englishMeaning: 'Exercise', article: 'die', plural: 'Übungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Wörterbuch', englishMeaning: 'Dictionary', article: 'das', plural: 'Wörterbücher', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Kugelschreiber', englishMeaning: 'Pen', article: 'der', plural: 'Kugelschreiber', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Bleistift', englishMeaning: 'Pencil', article: 'der', plural: 'Bleistifte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Heft', englishMeaning: 'Notebook', article: 'das', plural: 'Hefte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      { germanWord: 'Tafel', englishMeaning: 'Blackboard', article: 'die', plural: 'Tafeln', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Education' },
      // --- Food & Drinks (expanded) ---
      { germanWord: 'Butter', englishMeaning: 'Butter', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Marmelade', englishMeaning: 'Jam', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Wurst', englishMeaning: 'Sausage', article: 'die', plural: 'Würste', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Schinken', englishMeaning: 'Ham', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Reis', englishMeaning: 'Rice', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Nudeln', englishMeaning: 'Pasta/Noodles', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Kartoffel', englishMeaning: 'Potato', article: 'die', plural: 'Kartoffeln', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Tomate', englishMeaning: 'Tomato', article: 'die', plural: 'Tomaten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Zwiebel', englishMeaning: 'Onion', article: 'die', plural: 'Zwiebeln', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Zucker', englishMeaning: 'Sugar', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Salz', englishMeaning: 'Salt', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Öl', englishMeaning: 'Oil', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Saft', englishMeaning: 'Juice', article: 'der', plural: 'Säfte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Bier', englishMeaning: 'Beer', article: 'das', plural: 'Biere', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Wein', englishMeaning: 'Wine', article: 'der', plural: 'Weine', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Getränk', englishMeaning: 'Drink/Beverage', article: 'das', plural: 'Getränke', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Speisekarte', englishMeaning: 'Menu', article: 'die', plural: 'Speisekarten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Rechnung', englishMeaning: 'Bill/Invoice', article: 'die', plural: 'Rechnungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food', exampleSentence: 'Die Rechnung, bitte!' },
      { germanWord: 'Frühstück', englishMeaning: 'Breakfast', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Mittagessen', englishMeaning: 'Lunch', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Abendessen', englishMeaning: 'Dinner', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Teller', englishMeaning: 'Plate', article: 'der', plural: 'Teller', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Glas', englishMeaning: 'Glass', article: 'das', plural: 'Gläser', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Tasse', englishMeaning: 'Cup', article: 'die', plural: 'Tassen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Flasche', englishMeaning: 'Bottle', article: 'die', plural: 'Flaschen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Löffel', englishMeaning: 'Spoon', article: 'der', plural: 'Löffel', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Messer', englishMeaning: 'Knife', article: 'das', plural: 'Messer', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      { germanWord: 'Gabel', englishMeaning: 'Fork', article: 'die', plural: 'Gabeln', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Food' },
      // --- Shopping (expanded) ---
      { germanWord: 'Jacke', englishMeaning: 'Jacket', article: 'die', plural: 'Jacken', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Mantel', englishMeaning: 'Coat', article: 'der', plural: 'Mäntel', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Rock', englishMeaning: 'Skirt', article: 'der', plural: 'Röcke', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Pullover', englishMeaning: 'Sweater', article: 'der', plural: 'Pullover', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'T-Shirt', englishMeaning: 'T-shirt', article: 'das', plural: 'T-Shirts', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Bluse', englishMeaning: 'Blouse', article: 'die', plural: 'Blusen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Mütze', englishMeaning: 'Cap/Hat', article: 'die', plural: 'Mützen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Größe', englishMeaning: 'Size', article: 'die', plural: 'Größen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Kasse', englishMeaning: 'Checkout/Cash register', article: 'die', plural: 'Kassen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Angebot', englishMeaning: 'Offer/Special', article: 'das', plural: 'Angebote', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Preis', englishMeaning: 'Price', article: 'der', plural: 'Preise', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Euro', englishMeaning: 'Euro', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      { germanWord: 'Cent', englishMeaning: 'Cent', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Shopping' },
      // --- Transport (expanded) ---
      { germanWord: 'Flugzeug', englishMeaning: 'Airplane', article: 'das', plural: 'Flugzeuge', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Flughafen', englishMeaning: 'Airport', article: 'der', plural: 'Flughäfen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Haltestelle', englishMeaning: 'Bus/tram stop', article: 'die', plural: 'Haltestellen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'U-Bahn', englishMeaning: 'Subway', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Straßenbahn', englishMeaning: 'Tram', article: 'die', plural: 'Straßenbahnen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Gleis', englishMeaning: 'Platform/Track', article: 'das', plural: 'Gleise', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Abfahrt', englishMeaning: 'Departure', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Ankunft', englishMeaning: 'Arrival', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      { germanWord: 'Verspätung', englishMeaning: 'Delay', article: 'die', plural: 'Verspätungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Transport' },
      // --- Places (expanded) ---
      { germanWord: 'Park', englishMeaning: 'Park', article: 'der', plural: 'Parks', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Kirche', englishMeaning: 'Church', article: 'die', plural: 'Kirchen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Museum', englishMeaning: 'Museum', article: 'das', plural: 'Museen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Bibliothek', englishMeaning: 'Library', article: 'die', plural: 'Bibliotheken', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Rathaus', englishMeaning: 'Town hall', article: 'das', plural: 'Rathäuser', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Markt', englishMeaning: 'Market', article: 'der', plural: 'Märkte', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Platz', englishMeaning: 'Square/Place', article: 'der', plural: 'Plätze', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Kino', englishMeaning: 'Cinema', article: 'das', plural: 'Kinos', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Theater', englishMeaning: 'Theatre', article: 'das', plural: 'Theater', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Schwimmbad', englishMeaning: 'Swimming pool', article: 'das', plural: 'Schwimmbäder', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Spielplatz', englishMeaning: 'Playground', article: 'der', plural: 'Spielplätze', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Bäckerei', englishMeaning: 'Bakery', article: 'die', plural: 'Bäckereien', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      { germanWord: 'Metzgerei', englishMeaning: 'Butcher shop', article: 'die', plural: 'Metzgereien', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Places' },
      // --- Directions ---
      { germanWord: 'links', englishMeaning: 'left', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'rechts', englishMeaning: 'right', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'geradeaus', englishMeaning: 'straight ahead', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'oben', englishMeaning: 'above/upstairs', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'unten', englishMeaning: 'below/downstairs', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'neben', englishMeaning: 'next to', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'zwischen', englishMeaning: 'between', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'gegenüber', englishMeaning: 'across from/opposite', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'Ecke', englishMeaning: 'Corner', article: 'die', plural: 'Ecken', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'Kreuzung', englishMeaning: 'Intersection', article: 'die', plural: 'Kreuzungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Directions' },
      { germanWord: 'Ampel', englishMeaning: 'Traffic light', article: 'die', plural: 'Ampeln', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Directions' },
      // --- Missing Critical Verbs ---
      { germanWord: 'anfangen', englishMeaning: 'to start/begin', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Der Kurs fängt um 9 Uhr an.' },
      { germanWord: 'aufhören', englishMeaning: 'to stop/cease', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'aufmachen', englishMeaning: 'to open', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'zumachen', englishMeaning: 'to close', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'bekommen', englishMeaning: 'to receive/get', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'bringen', englishMeaning: 'to bring', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'einladen', englishMeaning: 'to invite', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'geben', englishMeaning: 'to give', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Es gibt einen Park.' },
      { germanWord: 'nehmen', englishMeaning: 'to take', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'stellen', englishMeaning: 'to put (standing)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'legen', englishMeaning: 'to put (lying)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'vergessen', englishMeaning: 'to forget', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'warten', englishMeaning: 'to wait', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Bitte warten Sie hier.' },
      { germanWord: 'zeigen', englishMeaning: 'to show', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'erklären', englishMeaning: 'to explain', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'tragen', englishMeaning: 'to carry/wear', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'laufen', englishMeaning: 'to run/walk', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'schwimmen', englishMeaning: 'to swim', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'tanzen', englishMeaning: 'to dance', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'singen', englishMeaning: 'to sing', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'besuchen', englishMeaning: 'to visit', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'dürfen', englishMeaning: 'may / to be allowed', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'sollen', englishMeaning: 'should / to be supposed to', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'glauben', englishMeaning: 'to believe', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'meinen', englishMeaning: 'to mean/think', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'passen', englishMeaning: 'to fit', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'gefallen', englishMeaning: 'to please/like', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Das Kleid gefällt mir.' },
      { germanWord: 'schmecken', englishMeaning: 'to taste', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'kosten', englishMeaning: 'to cost', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs', exampleSentence: 'Was kostet das?' },
      { germanWord: 'bestellen', englishMeaning: 'to order', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'umsteigen', englishMeaning: 'to change/transfer', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'aussteigen', englishMeaning: 'to get off', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'einsteigen', englishMeaning: 'to get on/board', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'einkaufen', englishMeaning: 'to shop', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'anrufen', englishMeaning: 'to call (phone)', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'fernsehen', englishMeaning: 'to watch TV', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      { germanWord: 'spazieren gehen', englishMeaning: 'to go for a walk', partOfSpeech: 'verb', cefrLevel: 'A1.1', topic: 'Verbs' },
      // --- Adjectives (expanded) ---
      { germanWord: 'richtig', englishMeaning: 'correct/right', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'falsch', englishMeaning: 'wrong/false', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'leer', englishMeaning: 'empty', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'voll', englishMeaning: 'full', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'leicht', englishMeaning: 'easy/light', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'schwer', englishMeaning: 'heavy/difficult', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'lang', englishMeaning: 'long', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'kurz', englishMeaning: 'short (length)', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'breit', englishMeaning: 'wide', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'dünn', englishMeaning: 'thin', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'dick', englishMeaning: 'thick/fat', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'laut', englishMeaning: 'loud', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'leise', englishMeaning: 'quiet', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'dunkel', englishMeaning: 'dark', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'hell', englishMeaning: 'bright/light', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'sauber', englishMeaning: 'clean', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'schmutzig', englishMeaning: 'dirty', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'nett', englishMeaning: 'nice/kind', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'lustig', englishMeaning: 'funny', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'müde', englishMeaning: 'tired', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'hungrig', englishMeaning: 'hungry', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'durstig', englishMeaning: 'thirsty', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'froh', englishMeaning: 'glad/happy', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'traurig', englishMeaning: 'sad', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'fertig', englishMeaning: 'ready/finished', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'frei', englishMeaning: 'free', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Adjectives' },
      { germanWord: 'verheiratet', englishMeaning: 'married', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'ledig', englishMeaning: 'single (unmarried)', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Personal' },
      // --- More function words / conjunctions ---
      { germanWord: 'aber', englishMeaning: 'but', partOfSpeech: 'conjunction', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'oder', englishMeaning: 'or', partOfSpeech: 'conjunction', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'und', englishMeaning: 'and', partOfSpeech: 'conjunction', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'denn', englishMeaning: 'because (conjunction)', partOfSpeech: 'conjunction', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'dann', englishMeaning: 'then', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'also', englishMeaning: 'so/therefore', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'auch', englishMeaning: 'also/too', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'noch', englishMeaning: 'still/yet', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'schon', englishMeaning: 'already', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'sehr', englishMeaning: 'very', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'gern(e)', englishMeaning: 'gladly/like to', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar', exampleSentence: 'Ich lese gern.' },
      { germanWord: 'zusammen', englishMeaning: 'together', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'allein', englishMeaning: 'alone', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Grammar' },
      // --- Question words ---
      { germanWord: 'warum', englishMeaning: 'why', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Questions' },
      { germanWord: 'wann', englishMeaning: 'when', partOfSpeech: 'adverb', cefrLevel: 'A1.1', topic: 'Questions' },
      { germanWord: 'wie viel', englishMeaning: 'how much', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Questions' },
      { germanWord: 'wie viele', englishMeaning: 'how many', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Questions' },
      { germanWord: 'welcher', englishMeaning: 'which', partOfSpeech: 'pronoun', cefrLevel: 'A1.1', topic: 'Questions' },
      // --- Common phrases (Goethe A1) ---
      { germanWord: 'Wie geht es Ihnen?', englishMeaning: 'How are you? (formal)', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Wie geht\'s?', englishMeaning: 'How are you? (informal)', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Es tut mir leid', englishMeaning: 'I\'m sorry', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Kein Problem', englishMeaning: 'No problem', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Greetings' },
      { germanWord: 'Ich verstehe nicht', englishMeaning: 'I don\'t understand', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'Sprechen Sie Englisch?', englishMeaning: 'Do you speak English?', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'Wie bitte?', englishMeaning: 'Pardon?', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Basics' },
      { germanWord: 'Noch einmal, bitte', englishMeaning: 'Once more, please', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Basics' },
      // --- Family (expanded) ---
      { germanWord: 'Großmutter', englishMeaning: 'Grandmother', article: 'die', plural: 'Großmütter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Großvater', englishMeaning: 'Grandfather', article: 'der', plural: 'Großväter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Oma', englishMeaning: 'Grandma', article: 'die', plural: 'Omas', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Opa', englishMeaning: 'Grandpa', article: 'der', plural: 'Opas', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Sohn', englishMeaning: 'Son', article: 'der', plural: 'Söhne', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Tochter', englishMeaning: 'Daughter', article: 'die', plural: 'Töchter', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Baby', englishMeaning: 'Baby', article: 'das', plural: 'Babys', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Onkel', englishMeaning: 'Uncle', article: 'der', plural: 'Onkel', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      { germanWord: 'Tante', englishMeaning: 'Aunt', article: 'die', plural: 'Tanten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Family' },
      // --- Hobbies (expanded) ---
      { germanWord: 'Hobby', englishMeaning: 'Hobby', article: 'das', plural: 'Hobbys', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Fußball', englishMeaning: 'Football/Soccer', article: 'der', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Tennis', englishMeaning: 'Tennis', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Fahrrad fahren', englishMeaning: 'to ride a bicycle', partOfSpeech: 'phrase', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Gitarre', englishMeaning: 'Guitar', article: 'die', plural: 'Gitarren', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Foto', englishMeaning: 'Photo', article: 'das', plural: 'Fotos', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      { germanWord: 'Reise', englishMeaning: 'Trip/Journey', article: 'die', plural: 'Reisen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Hobbies' },
      // --- Numbers (cardinal) ---
      { germanWord: 'null', englishMeaning: 'zero', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'eins', englishMeaning: 'one', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'zwei', englishMeaning: 'two', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'drei', englishMeaning: 'three', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'vier', englishMeaning: 'four', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'fünf', englishMeaning: 'five', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'sechs', englishMeaning: 'six', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'sieben', englishMeaning: 'seven', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'acht', englishMeaning: 'eight', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'neun', englishMeaning: 'nine', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'zehn', englishMeaning: 'ten', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'zwanzig', englishMeaning: 'twenty', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'dreißig', englishMeaning: 'thirty', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'hundert', englishMeaning: 'hundred', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      { germanWord: 'tausend', englishMeaning: 'thousand', partOfSpeech: 'numeral', cefrLevel: 'A1.1', topic: 'Numbers' },
      // --- Misc essential ---
      { germanWord: 'Geburtstag', englishMeaning: 'Birthday', article: 'der', plural: 'Geburtstage', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal', exampleSentence: 'Herzlichen Glückwunsch zum Geburtstag!' },
      { germanWord: 'Geschenk', englishMeaning: 'Gift/Present', article: 'das', plural: 'Geschenke', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Fest', englishMeaning: 'Party/Festival', article: 'das', plural: 'Feste', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Einladung', englishMeaning: 'Invitation', article: 'die', plural: 'Einladungen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Personal' },
      { germanWord: 'Nachricht', englishMeaning: 'Message/News', article: 'die', plural: 'Nachrichten', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'E-Mail', englishMeaning: 'E-mail', article: 'die', plural: 'E-Mails', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Internet', englishMeaning: 'Internet', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Fernseher', englishMeaning: 'Television', article: 'der', plural: 'Fernseher', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Schlüssel', englishMeaning: 'Key', article: 'der', plural: 'Schlüssel', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Tasche', englishMeaning: 'Bag', article: 'die', plural: 'Taschen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Regenschirm', englishMeaning: 'Umbrella', article: 'der', plural: 'Regenschirme', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Brille', englishMeaning: 'Glasses', article: 'die', plural: 'Brillen', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Daily Life' },
      { germanWord: 'Uhrzeit', englishMeaning: 'Time (of day)', article: 'die', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time' },
      { germanWord: 'Viertel', englishMeaning: 'Quarter', article: 'das', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time', exampleSentence: 'Es ist Viertel nach drei.' },
      { germanWord: 'halb', englishMeaning: 'half', partOfSpeech: 'adjective', cefrLevel: 'A1.1', topic: 'Time', exampleSentence: 'Es ist halb vier.' },
      { germanWord: 'Monat', englishMeaning: 'Month', article: 'der', plural: 'Monate', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time' },
      { germanWord: 'Jahr', englishMeaning: 'Year', article: 'das', plural: 'Jahre', partOfSpeech: 'noun', cefrLevel: 'A1.1', topic: 'Time' },
      // --- Prepositions (expanded) ---
      { germanWord: 'an', englishMeaning: 'at/on', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'auf', englishMeaning: 'on/onto', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'unter', englishMeaning: 'under', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'über', englishMeaning: 'over/above', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'vor', englishMeaning: 'in front of / before', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'hinter', englishMeaning: 'behind', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'zu', englishMeaning: 'to', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'bei', englishMeaning: 'at / near', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'aus', englishMeaning: 'from / out of', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar', exampleSentence: 'Ich komme aus Indien.' },
      { germanWord: 'seit', englishMeaning: 'since / for (time)', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'bis', englishMeaning: 'until / to', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar' },
      { germanWord: 'um', englishMeaning: 'at (time) / around', partOfSpeech: 'preposition', cefrLevel: 'A1.1', topic: 'Grammar', exampleSentence: 'Der Kurs beginnt um 9 Uhr.' },
    ];

    await db.insert(schema.vocabulary).values(vocabData);

    // ========================================
    // GRAMMAR POINTS — Core A1–A2 (with 2 new additions)
    // ========================================
    console.log('Inserting grammar points...');
    const grammarData = [
      { title: 'Personal Pronouns', explanation: 'ich, du, er/sie/es, wir, ihr, sie/Sie', pattern: 'ich → du → er/sie/es → wir → ihr → sie/Sie', cefrLevel: 'A1.1', topic: 'Pronouns' },
      { title: 'Verb "sein" (to be)', explanation: 'The most important German verb. Irregular conjugation.', pattern: 'ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind', cefrLevel: 'A1.1', topic: 'Verbs' },
      { title: 'Verb "haben" (to have)', explanation: 'Second most important verb. Used for possession and perfect tense.', pattern: 'ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie/Sie haben', cefrLevel: 'A1.1', topic: 'Verbs' },
      { title: 'Present Tense (Präsens)', explanation: 'Regular verb conjugation by removing -en and adding endings.', pattern: '-e, -st, -t, -en, -t, -en', cefrLevel: 'A1.1', topic: 'Verbs' },
      { title: 'W-Questions (W-Fragen)', explanation: 'Questions starting with W-words. Verb comes second.', pattern: 'W-Wort + Verb + Subjekt + ...? → Wie heißt du?', cefrLevel: 'A1.1', topic: 'Questions' },
      { title: 'Yes/No Questions', explanation: 'Questions answered with ja/nein. Verb comes first.', pattern: 'Verb + Subjekt + ...? → Bist du Student?', cefrLevel: 'A1.1', topic: 'Questions' },
      { title: 'Definite Articles (der/die/das)', explanation: 'German has 3 genders. Every noun has a fixed gender.', pattern: 'der (masculine), die (feminine), das (neuter)', cefrLevel: 'A1.1', topic: 'Articles' },
      { title: 'Indefinite Articles (ein/eine)', explanation: 'Used when referring to something non-specific.', pattern: 'ein (masc/neut), eine (fem), kein (negation)', cefrLevel: 'A1.1', topic: 'Articles' },
      { title: 'Possessive Determiners', explanation: 'Show ownership. Follow the same endings as ein/eine.', pattern: 'mein, dein, sein, ihr, unser, euer, ihr/Ihr', cefrLevel: 'A1.1', topic: 'Pronouns' },
      { title: 'Accusative Case (Akkusativ)', explanation: 'Used for direct objects. Only masculine article changes.', pattern: 'der → den, ein → einen. Die/das stay the same.', cefrLevel: 'A1.1', topic: 'Cases' },
      { title: 'Negation (nicht/kein)', explanation: '"nicht" negates verbs/adjectives. "kein" negates nouns with ein.', pattern: 'Ich trinke nicht. Ich habe keinen Kaffee.', cefrLevel: 'A1.1', topic: 'Negation' },
      { title: 'Separable Verbs (Trennbare Verben)', explanation: 'Verbs with a prefix that separates in present tense.', pattern: 'aufstehen → Ich stehe um 7 Uhr auf.', cefrLevel: 'A1.1', topic: 'Verbs' },
      { title: 'Modal Verbs', explanation: 'können, müssen, wollen, dürfen, sollen, möchten', pattern: 'Modalverb (pos. 2) + Infinitiv (Ende)', cefrLevel: 'A1.1', topic: 'Verbs' },
      { title: 'Sentence Structure (Satzbau)', explanation: 'German uses V2 word order: verb always in position 2.', pattern: 'Subjekt + Verb + Objekt → Ich lerne Deutsch.', cefrLevel: 'A1.1', topic: 'Word Order' },
      // NEW: Temporal Prepositions
      { title: 'Temporal Prepositions (am, um, im)', explanation: 'Used to express time. "am" for days/parts of day, "um" for clock time, "im" for months/seasons.', pattern: 'am Montag, am Abend, um 8 Uhr, im Januar, im Sommer', cefrLevel: 'A1.1', topic: 'Prepositions' },
      // NEW: es gibt + Akkusativ
      { title: 'es gibt + Accusative', explanation: '"Es gibt" means "there is/there are". Always followed by accusative case.', pattern: 'Es gibt einen Park. Es gibt viele Restaurants.', cefrLevel: 'A1.1', topic: 'Expressions' },
      { title: 'Dative Case (Dativ)', explanation: 'Used for indirect objects and after certain prepositions.', pattern: 'dem (masc/neut), der (fem), den (plural)', cefrLevel: 'A1.2', topic: 'Cases' },
      { title: 'Perfect Tense (Perfekt)', explanation: 'Used for talking about the past. haben/sein + past participle.', pattern: 'Ich habe gemacht. Ich bin gegangen.', cefrLevel: 'A1.2', topic: 'Tenses' },
      { title: 'Conjunctions (und, aber, oder)', explanation: 'Connect two main clauses. Do not change word order.', pattern: 'Ich lerne Deutsch und ich arbeite.', cefrLevel: 'A1.2', topic: 'Connectors' },
      { title: 'Subordinate Clauses (weil, dass)', explanation: 'The verb moves to the end of the clause.', pattern: 'Ich lerne, weil ich nach Deutschland will.', cefrLevel: 'A2.1', topic: 'Word Order' },
      { title: 'Comparative & Superlative', explanation: 'Comparing things. Add -er for comparative, am -sten for superlative.', pattern: 'groß → größer → am größten', cefrLevel: 'A2.1', topic: 'Adjectives' },
      { title: 'Reflexive Verbs', explanation: 'Verbs where the subject acts on itself.', pattern: 'sich freuen → Ich freue mich.', cefrLevel: 'A2.1', topic: 'Verbs' },
      { title: 'Adjective Endings', explanation: 'Adjectives change endings before nouns based on gender, case, and article type.', pattern: 'der große Mann, ein großer Mann', cefrLevel: 'A2.1', topic: 'Adjectives' },
      { title: 'Simple Past (Präteritum)', explanation: 'Used mainly for sein, haben, and modal verbs in past tense.', pattern: 'war, hatte, konnte, musste, wollte', cefrLevel: 'A2.2', topic: 'Tenses' },
      { title: 'Two-Way Prepositions', explanation: 'Use accusative for movement (wohin?) and dative for location (wo?).', pattern: 'Ich gehe in die Küche. Ich bin in der Küche.', cefrLevel: 'A2.2', topic: 'Prepositions' },
    ];

    await db.insert(schema.grammarPoints).values(grammarData);

    console.log('✅ Comprehensive seed completed: 26 modules, 70+ lessons, 650+ vocabulary, 25 grammar points');
  } catch (error) {
    console.error('❌ Error during seeding:', error);
  } finally {
    client.close();
    process.exit(0);
  }
}

seed();

